### ISSUE TITLE
Hygieia UI - Repo form not saving [Inquiry]

### ISSUE THREAD

**Issue by abjoseph** [samwiskow/nodeDemo#10]
Hi @samwiskow,

You made a comment a while back on the Hygieia UI repo about the old version of the config.js --> https://github.com/hygieia/UI/issues/172#issuecomment-784994226. I am currently running into this issue, and I was hoping that you either have the fixes/changes you made or the commit hash of the repo-config.ts file from the old repo since I can't seem to find that version from which you took that code snippet.

Apologies for the random issue here but it's the only way I could reach given that GitHub doesn't have a messaging feature.

**Comment by samwiskow** [comment]
I decided to stop pursuing Hygieia as there was too much that didn't work correctly and not enough documentation
